name: ZSL Continuous Integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**/README.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**/README.md'

jobs:
  test-and-fmt:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout zsl
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.17.0-dev.813+2153f8143

      - name: Run unit tests
        run: zig build test --summary all

      - name: Check formatting
        run: zig fmt --check src/ examples/ build.zig benchmarks/

      - name: Run example subset
        run: zig build example example-vector example-blas example-lapack-qr
